name: .NET CI/CD pipeline

env:
  # The name of the project to build and package
  PROJECT_NAME: Sweaj.Patterns

  # The path to the project file to build and package
  PROJECT_FILE: src/Sweaj.Patterns/Sweaj.Patterns.csproj

  # The dotnet version to build and publish with
  DOTNET_VERSION: 7.0.x

  # The build configuration to use (e.g. Debug or Release)
  BUILD_CONFIGURATION: Release

  # The version number to use for the package
  PACKAGE_VERSION: 1.0.0

  # The directory to publish the package to
  PACKAGE_DIRECTORY: nuget/

  # The API key for the NuGet repository
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  # The URL of the NuGet repository to publish the package to
  NUGET_REPOSITORY_URL: https://api.nuget.org/v3/index.json

on:
  push:
    branches:
      - main
      - develop 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_FILE }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_FILE }} -c ${{ env.BUILD_CONFIGURATION }}

    - name: Test
      run: dotnet test ${{ env.PROJECT_FILE }} -c ${{ env.BUILD_CONFIGURATION }}

    - name: Publish package
      run: dotnet pack ${{ env.PROJECT_FILE }} -c ${{ env.BUILD_CONFIGURATION }} --version-suffix $GITHUB_RUN_NUMBER --output ${{ env.PACKAGE_DIRECTORY }}

    - name: Push package to NuGet
      run: dotnet nuget push ${{ env.PACKAGE_DIRECTORY }}*.nupkg --api-key ${{ env.NUGET_API_KEY }}--source "${{ env.NUGET_REPOSITORY_URL }}"